FROM scratch
WORKDIR /app
COPY .build/staging/_shared/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY .build/staging/devflow-app-service/devflow-app-service ./devflow-app-service
COPY .build/staging/devflow-app-service/docs ./docs
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
EXPOSE 8081
USER 65532:65532
ENTRYPOINT ["/app/devflow-app-service"]
