definitions:
  github_com_bsonger_devflow-app-service_pkg_domain.Application:
    properties:
      active_image_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      project_id:
        type: string
      repo_address:
        type: string
      updated_at:
        type: string
    type: object
  github_com_bsonger_devflow-app-service_pkg_domain.Cluster:
    properties:
      argocd_cluster_name:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      kubeconfig:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      onboarding_checked_at:
        type: string
      onboarding_error:
        type: string
      onboarding_ready:
        type: boolean
      server:
        type: string
      updated_at:
        type: string
    type: object
  github_com_bsonger_devflow-app-service_pkg_domain.Environment:
    properties:
      cluster_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  github_com_bsonger_devflow-app-service_pkg_domain.LabelItem:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  github_com_bsonger_devflow-app-service_pkg_domain.Project:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application:
    properties:
      data:
        $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Application'
    type: object
  httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Cluster:
    properties:
      data:
        $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Cluster'
    type: object
  httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Environment:
    properties:
      data:
        $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Environment'
    type: object
  httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project:
    properties:
      data:
        $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Project'
    type: object
  httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Application'
        type: array
      pagination:
        $ref: '#/definitions/httpx.Pagination'
    type: object
  httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Cluster:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Cluster'
        type: array
      pagination:
        $ref: '#/definitions/httpx.Pagination'
    type: object
  httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Environment:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Environment'
        type: array
      pagination:
        $ref: '#/definitions/httpx.Pagination'
    type: object
  httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Project'
        type: array
      pagination:
        $ref: '#/definitions/httpx.Pagination'
    type: object
  httpx.Pagination:
    properties:
      enabled:
        type: boolean
      limit:
        type: integer
      offset:
        type: integer
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  pkg_api.CreateApplicationRequest:
    properties:
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      project_id:
        type: string
      repo_address:
        type: string
    type: object
  pkg_api.CreateClusterRequest:
    properties:
      argocd_cluster_name:
        type: string
      description:
        type: string
      kubeconfig:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      server:
        type: string
    required:
    - kubeconfig
    - name
    - server
    type: object
  pkg_api.CreateEnvironmentRequest:
    properties:
      cluster_id:
        type: string
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
    required:
    - cluster_id
    - name
    type: object
  pkg_api.CreateProjectRequest:
    properties:
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
    type: object
  pkg_api.UpdateActiveImageRequest:
    properties:
      image_id:
        type: string
    required:
    - image_id
    type: object
  pkg_api.UpdateApplicationRequest:
    properties:
      active_image_id:
        type: string
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      project_id:
        type: string
      repo_address:
        type: string
    type: object
  pkg_api.UpdateClusterRequest:
    properties:
      argocd_cluster_name:
        type: string
      description:
        type: string
      kubeconfig:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      server:
        type: string
    required:
    - kubeconfig
    - name
    - server
    type: object
  pkg_api.UpdateEnvironmentRequest:
    properties:
      cluster_id:
        type: string
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
    required:
    - cluster_id
    - name
    type: object
  pkg_api.UpdateProjectRequest:
    properties:
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/applications:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 获取应用列表
      tags:
      - Application
    post:
      consumes:
      - application/json
      description: 创建一个新的应用
      parameters:
      - description: Application Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.CreateApplicationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 创建应用
      tags:
      - Application
  /api/v1/applications/{id}:
    delete:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除应用
      tags:
      - Application
    get:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 获取应用
      tags:
      - Application
    put:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      - description: Application Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateApplicationRequest'
      responses:
        "204":
          description: No Content
      summary: 更新应用
      tags:
      - Application
  /api/v1/applications/{id}/active_image:
    patch:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      - description: Active Image Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateActiveImageRequest'
      responses:
        "204":
          description: No Content
      summary: 更新应用的 Active Image
      tags:
      - Application
  /api/v1/clusters:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Cluster'
      summary: 获取集群列表
      tags:
      - Cluster
    post:
      consumes:
      - application/json
      description: 创建一个新的集群
      parameters:
      - description: Cluster Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.CreateClusterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Cluster'
      summary: 创建集群
      tags:
      - Cluster
  /api/v1/clusters/{id}:
    delete:
      parameters:
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除集群
      tags:
      - Cluster
    get:
      parameters:
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Cluster'
      summary: 获取集群
      tags:
      - Cluster
    put:
      parameters:
      - description: Cluster ID
        in: path
        name: id
        required: true
        type: string
      - description: Cluster Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateClusterRequest'
      responses:
        "204":
          description: No Content
      summary: 更新集群
      tags:
      - Cluster
  /api/v1/environments:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Environment'
      summary: 获取环境列表
      tags:
      - Environment
    post:
      consumes:
      - application/json
      description: 创建一个新的环境
      parameters:
      - description: Environment Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.CreateEnvironmentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Environment'
      summary: 创建环境
      tags:
      - Environment
  /api/v1/environments/{id}:
    delete:
      parameters:
      - description: Environment ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除环境
      tags:
      - Environment
    get:
      parameters:
      - description: Environment ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Environment'
      summary: 获取环境
      tags:
      - Environment
    put:
      parameters:
      - description: Environment ID
        in: path
        name: id
        required: true
        type: string
      - description: Environment Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateEnvironmentRequest'
      responses:
        "204":
          description: No Content
      summary: 更新环境
      tags:
      - Environment
  /api/v1/projects:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project'
      summary: 获取项目列表
      tags:
      - Project
    post:
      consumes:
      - application/json
      description: 创建一个新的项目
      parameters:
      - description: Project Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project'
      summary: 创建项目
      tags:
      - Project
  /api/v1/projects/{id}:
    delete:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除项目
      tags:
      - Project
    get:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project'
      summary: 获取项目
      tags:
      - Project
    put:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Project Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateProjectRequest'
      responses:
        "204":
          description: No Content
      summary: 更新项目
      tags:
      - Project
  /api/v1/projects/{id}/applications:
    get:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 获取项目下的应用列表
      tags:
      - Project
swagger: "2.0"
