definitions:
  github_com_bsonger_devflow-app-service_pkg_domain.Application:
    properties:
      active_image_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      project_id:
        type: string
      repo_address:
        type: string
      updated_at:
        type: string
    type: object
  github_com_bsonger_devflow-app-service_pkg_domain.LabelItem:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  github_com_bsonger_devflow-app-service_pkg_domain.Project:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application:
    properties:
      data:
        $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Application'
    type: object
  httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project:
    properties:
      data:
        $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Project'
    type: object
  httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Application'
        type: array
      pagination:
        $ref: '#/definitions/httpx.Pagination'
    type: object
  httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.Project'
        type: array
      pagination:
        $ref: '#/definitions/httpx.Pagination'
    type: object
  httpx.Pagination:
    properties:
      enabled:
        type: boolean
      limit:
        type: integer
      offset:
        type: integer
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  pkg_api.CreateApplicationRequest:
    properties:
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      project_id:
        type: string
      repo_address:
        type: string
    type: object
  pkg_api.CreateProjectRequest:
    properties:
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
    type: object
  pkg_api.UpdateActiveImageRequest:
    properties:
      image_id:
        type: string
    required:
    - image_id
    type: object
  pkg_api.UpdateApplicationRequest:
    properties:
      active_image_id:
        type: string
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
      project_id:
        type: string
      repo_address:
        type: string
    type: object
  pkg_api.UpdateProjectRequest:
    properties:
      description:
        type: string
      labels:
        items:
          $ref: '#/definitions/github_com_bsonger_devflow-app-service_pkg_domain.LabelItem'
        type: array
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/applications:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 获取应用列表
      tags:
      - Application
    post:
      consumes:
      - application/json
      description: 创建一个新的应用
      parameters:
      - description: Application Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.CreateApplicationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 创建应用
      tags:
      - Application
  /api/v1/applications/{id}:
    delete:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除应用
      tags:
      - Application
    get:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 获取应用
      tags:
      - Application
    put:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      - description: Application Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateApplicationRequest'
      responses:
        "204":
          description: No Content
      summary: 更新应用
      tags:
      - Application
  /api/v1/applications/{id}/active_image:
    patch:
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        type: string
      - description: Active Image Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateActiveImageRequest'
      responses:
        "204":
          description: No Content
      summary: 更新应用的 Active Image
      tags:
      - Application
  /api/v1/projects:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project'
      summary: 获取项目列表
      tags:
      - Project
    post:
      consumes:
      - application/json
      description: 创建一个新的项目
      parameters:
      - description: Project Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project'
      summary: 创建项目
      tags:
      - Project
  /api/v1/projects/{id}:
    delete:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除项目
      tags:
      - Project
    get:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.DataResponse-github_com_bsonger_devflow-app-service_pkg_domain_Project'
      summary: 获取项目
      tags:
      - Project
    put:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Project Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pkg_api.UpdateProjectRequest'
      responses:
        "204":
          description: No Content
      summary: 更新项目
      tags:
      - Project
  /api/v1/projects/{id}/applications:
    get:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpx.ListResponse-github_com_bsonger_devflow-app-service_pkg_domain_Application'
      summary: 获取项目下的应用列表
      tags:
      - Project
swagger: "2.0"
